language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
dist: trusty
before_script:
  - cp .env.example .env
  - psql -c "CREATE DATABASE tadb;" -U postgres
  - psql -c "CREATE USER tauser WITH LOGIN PASSWORD 'password';" -U postgres
  - psql -c "ALTER ROLE tauser WITH CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE tadb TO tauser;" -U postgres
before_install:
  - export DJANGO_SETTINGS_MODULE=ta_portal.settings
install:
  - pip3 install pipenv
  - pipenv install --dev
script:
  - pipenv shell
  - cd src
  - flake8 .
  - python manage.py makemigrations
  - python manage.py migrate
  - cd ../frontend
  - npm install
  - npm run build
